### PR TITLE
Update to tslint v4.0.1

### PR DESCRIPTION
**Pull request by mdurling**
* Remove no-unreachable
* Remove no-unused-variable
* Update package.json
* Regenerate test data

### CODE REVIEW

**Comment by mdurling** [comment]
This PR contains all of the necessary package update, rule changes, and testcase updates.

**Comment by mdurling** [comment]
I am not sure why the Travis CI check is failing. It is passing when I run the tests locally.

**Comment by blakeembrey** [comment]
Probably waiting on https://github.com/buzinas/tslint-eslint-rules/pull/138.

**Comment by mdurling** [comment]
@blakeembrey Let me know if you need me to do anything else with this PR.

**Comment by jmlopez-rod** [comment]
[v3.0.0](https://www.npmjs.com/package/tslint-eslint-rules) has been released on npm. Let me know if you guys encounter any issues.

**Comment by mdurling** [comment]
@blakeembrey PR #14 has been updated to include [tslint-eslint-rules@3.0.0](https://www.npmjs.com/package/tslint-eslint-rules)

**Comment by unional** [comment]
@mdurling you beat me to it. 🌷

**Pull request merged**
